apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - nodejs
    - service
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
